### ISSUE TITLE
Remove default URIs and OPT to have application profiles define their own

### ISSUE THREAD

**Issue by fpalombini** [ace-wg/ace-key-groupcomm#110]
Remove that the root uris can be different for every profile. They all use the same and what specific application profile is used is per group (and that info is saved in each group).

**Comment by fpalombini** [comment]
@jimsch does it mean that we need to register a well-known URI for this document though? (only for this one and not for additional application profiles)

**Comment by jimsch** [comment]
One of two things need to happen.  1) register a will-known URI or 2) document how this would be found if a server decides to use a different URI.  This is the rt and directory thing that the ace framework is doing.

**Comment by fpalombini** [comment]
i think being consistent with what the framework does is probably the right choice.
