### ISSUE TITLE
ACE scope semantics: CBOR file-magic

### ISSUE THREAD

**Issue by chrysn** [ace-wg/ace-key-groupcomm#144]
Following up on IETF113 discussion, I think that the "extended scope format" can be vastly simplified by using [cbor-file-magic](https://datatracker.ietf.org/doc/draft-ietf-cbor-file-magic/):

Rather than specifying a new format and registry for scopes, the scopes within an audience that employs this mechanism would be disambiguated just like file formats. (They have common properties: Everybody assumes that their semantics are known from the context, but in the odd case they are not, eg. because an audience is used with different kinds of scopes).

Rather than becoming

```
extended_scope = #6.TBD_TAG(<< [semantics, scope] >>)
```

the extended scope could just be
```
extended_scope = #6.TAG_FOR_THESE_SEMANTICS(scope)
```

which, if TAG_FOR_THESE_SEMANTICS is allocated following the recommendations of cbor-file-magic (I guess it'd forego using the self-describing tag `#6.55799()` around it) equivalent to prefixing the encoded scope with 5 bytes specific to that tag. In particular, if for the scopes' semantics a content format is allocated (and there is already 290 for AIF with the default `;Toid=URI-local-part;Tperm=REST-method-set`), the tag is even already allocated, and if other AIF generalizations allocate their own content format, they also get the tag automatically.

The only down side I see is that the scope claims might grow in size, depending on the precise numbers allocated. But for example, if a 1+1 tag were chosen for the current TBD_TAG, depending on the length of the inner encoding, this might already be just as good or even better.

**Comment by marco-tiloca-sics** [comment]
Thanks for the good observation and input, I think it would be a good change!

When the "extended scope format" was added to -ace-key-groupcomm, the registration of one tag only and of on-demand semantics integers ended up preferred, compared to opening for the registration of multiple CBOR tags. But on the other hand I think all you've mentioned was not around yet :-)

> which, if TAG_FOR_THESE_SEMANTICS is allocated following the recommendations of cbor-file-magic (I guess it'd forego using the self-describing tag #6.55799() around it) equivalent to prefixing the encoded scope with 5 bytes specific to that tag.

Yes, TAG_FOR_THESE_SEMANTICS would be from the 4-byte range, and there is no need to further use the tag 55799.

> In particular, if for the scopes' semantics a content format is allocated (and there is already 290 for AIF with the default ;Toid=URI-local-part;Tperm=REST-method-set), the tag is even already allocated,

Yes, if scope uses exactly Generic AIF, the value of  TAG_FOR_THESE_SEMANTICS is 1668546850=1668546560+290.

Some guideline and pointer to -cbor-file-magic can be added for a more general case not relying on AIF.

> and if other AIF generalizations allocate their own content format, they also get the tag automatically.

Yes, for example the document -ace-key-groupcomm-oscore is defining the new data model AIF-OSCORE-GROUPCOMM [0] and registering a corresponding content-format, so it would also automatically have the corresponding value for its TAG_FOR_THESE_SEMANTICS.

> The only down side I see is that the scope claims might grow in size, depending on the precise numbers allocated. But for example, if a 1+1 tag were chosen for the current TBD_TAG, depending on the length of the inner encoding, this might already be just as good or even better.

I think it's more likely to be even better.

[0] As also discussed at IETF 113, that same data model would cover both the "user" scope entries defined in -ace-key-groupcomm-oscore and the "admin" scope entries defined in -ace-oscore-gm-admin, as possible to coexist in the same scope claim. The type of the different scope entries is distinguishable thanks to the least significant bit in their Tperm value, which would also have this meaning already from the revised definition of the data model.
