### ISSUE TITLE
Multiple Joins - Does it rekey?

### ISSUE THREAD

**Issue by jimsch** [ace-wg/ace-key-groupcomm#59]
The document does not suggest if the following is a situation where a KDC is supposed to do a key roll over or not.

1.  Client C posts to the KDC to join GroupA.
*** At this point a key rollover action is done
*** Time passes
2.  Client C posts to the KDC to join GroupA and it has not been removed for any reason.
*** At this point a key rollover action is/is not done?

**Comment by fpalombini** [comment]
I think this should be covered by the following sentence in section 4.2:

> If the application requires backward security, the KDC MUST generate new group keying material and securely distribute it to all the current group members, upon a new node's joining the group.

The key term being *new*. This would mean that in the scenario you describe above, the Client C is not a *new node* and key rollover is not initiated by KDC.

Is this not clear enough? Do we need to add more text explaining what "new" means here?

**Comment by jimsch** [comment]
Given that this becomes a specific test case for the group resource, I think that it should perhaps be highlighted.  I can easily argue that any time somebody does a join, they are by definition a new node joining the group.

**Comment by jimsch** [comment]
I think that the language "when the membership changes" is much clearer than "when a new node joins".
