### ISSUE TITLE
When are the public key  and proof of possession required to be present

### ISSUE THREAD

**Issue by jimsch** [ace-wg/ace-key-groupcomm#60]
I believe that one needs to look at the following cases:

1.  No public key with the right parameters has been associated with the token - in this case both the key and proof are required
2.  One public key with the right parameters has been associated with the token - in this case the following would seem to be fine a) neither are present, b) just the key is present (proof already has been done), c) both are present
3. Multiple public keys with the right parameters have been associated with the token - In this case the following would seem to be fine a) just the key is present (proof has already been done) or b) both are present

Such a change would seem to maximize the number of times that the public key can be omitted and an even greater number of times the proof can be omitted.  In the event that the proof is needed, the error would return a new server nonce to be used in the re-sent join message.

**Comment by fpalombini** [comment]
EDIT: this response is in preparation for Ace interim 15-04-2020

My main question is: what does this consideration applies to? It could apply to the joining process and to POST to pub-key (where the node post a new public key to the KDC). These are quite perpendicular though (1 -> joining, 2 -> pub-key, 3 -> not supported), so I am not sure what this adds… This could be covering the join – leave – rejoin with the same token process, that is not very well covered right now, is that something we need to expand on?

> I believe that one needs to look at the following cases:

> No public key with the right parameters has been associated with the token - in this case both the key and proof are required

What we do say is that key and proof of possession are required during join process if KDC collects and distribute keys, and the client is a sender. So one key will always be associated with the token. 1 is a quite convoluted way to say: “always at joining” (which we already say…) or is this supposed to cover another case?


> One public key with the right parameters has been associated with the token - in this case the following would seem to be fine a) neither are present, b) just the key is present (proof already has been done), c) both are present

Are we talking about after joining, posting a new pub key to the KDC? Then both are needed. Unless the key is the same…in which case it is useless to repost the same to pub-key.

> Multiple public keys with the right parameters have been associated with the token - In this case the following would seem to be fine a) just the key is present (proof has already been done) or b) both are present

The KDC only keeps one public key per node (see pub-key handler), this is not supported. In what case would the client want to associate more than one key? Is this something we want?


> Such a change would seem to maximize the number of times that the public key can be omitted and an even greater number of times the proof can be omitted. In the event that the proof is needed, the error would return a new server nonce to be used in the re-sent join message.

I think right now we already cover the case where the key and proof MUST be sent in each section. What are we missing?

**Comment by jimsch** [comment]
If I have a token that allows access to multiple groups, once I have done the POP on the signing key for that token, that POP can be propagated forward to any other group join which uses the same token.  I might end up with multiple keys for the single token with different keys.  This POP could potentially be propagated forward as tokens are updated.
