### ISSUE TITLE
Section 3.2 - Fix third to last paragraph on the token content

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#63]

**Comment by fpalombini** [comment]
@jimsch wrote: 

> * Section 3.2 - The third to last paragraph is incorrect, the token should
> have the expires AT not the expires IN parameter.  There is a solid
> assumption that in this case there is a common idea of a wall clock between
> all of the servers and there for stating a hard expiration time is more
> appropriate than an expires in moment.  Additionally, tokens will generally
> not include the rs_cnf even if it is in the response message and will
> include a cnf for an asymmetric key.  In short, this paragraph is just plain
> wrong.

This was leftover text that never got fixed. We will explicitly state what MUST (and what MAY) be included in the token.
