### ISSUE TITLE
Section 3.2 - AS returning same vs. new access token

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#64]

**Comment by fpalombini** [comment]
I have the feeling this might be leftovers, I don't see a reason now why the AS could not return the same access token (if it's still valid)... Whatever issues there could be about re-use of keying material MUST be dealt with by the application profile used (which OSCORE profile does with nonces, for example)

**Comment by jimsch** [comment]
the AS **MAY reply** with
