### ISSUE TITLE
Section 3.3 - array of informative parameters, not assuming an order

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#65]

**Comment by fpalombini** [comment]
@jimsch wrote: In Section 3.3 - As an input to your "make it an array" decisions,
remember that the order of scope elements that the client gave to the AS are
not necessarily the same order as are in the token.  I think you might just
need to collapse all three arrays into a single value in the map.

**Comment by fpalombini** [comment]
I am not sure what "collapse all three arrays in a single value in the map" means... 
But yes we need to deal with this:

Marco proposes the following:
```
“sign_info” : [
                        + [ gid,
                          sign_alg,
                          sign_parameters,
                          sign_key_parameters
                        ],
                     ]


“pub_key_enc” : [
                               + [ gid,
                                 pub_key_enc_per_group
                               ]
                            ]
```

I think this makes more sense:

```
“sign_info” : [
                        + [ gid,
                          sign_alg,
                          sign_parameters,
                          sign_key_parameters,
                          pub_key_enc
                        ]
                     ]
```

We are not allowing more than one pub key encoding anyway per group. I'll implement this, but please comment if you don't agree.

**Comment by jimsch** [comment]
Yes that was the type of thing I was thinking of.
