### ISSUE TITLE
Section 4.1.2.1 - Forward pointer to usage of 'control_path'

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#71]

**Comment by fpalombini** [comment]
Related to 'control_path', @jimsch asked: 

> 
> * In section 4.1.2.1 - What happens if a 'control_path' is provided but not
> supported - does that mean a bad request?
> 

What do you mean is provided but not supported? By the client? That should never happen, as the client will only set this field if it can support to host a resource at that URI.

**Comment by jimsch** [comment]
No by the server - it is the client providing this to the server.

**Comment by fpalombini** [comment]
Ah ok, you mean if the KDC does not support mechanism using that? Then it will just ignore that parameter I suppose... I will add a note about that.
