### ISSUE TITLE
Section 4.1.2.1 - 'exp' as integer only

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#73]

**Comment by fpalombini** [comment]
@jimsch said:

> * In section 4.1.2.1 - Unless you have a reason for allowing floating point
> for 'exp', make it integer only.  
> 

we mirrored that from the Ace 'exp' parameter, which is defined to be either int or floating point number, see https://tools.ietf.org/html/draft-ietf-ace-oauth-authz-33#section-5.7.4 . Any specific reason why we would want something different for the ace-group parameter?

**Comment by jimsch** [comment]
In retrospect, I think that allowing it to be a floating point is a general CWT error.  It was copied directly from CBOR but it means that all of the servers/clients now potentially need to have support for a floating point library to evaluate this field.  Making it only an integer means that is not an issue.  This has been raised as a RATS issue

**Comment by fpalombini** [comment]
That makes sense. I'll change it to only int. Maybe it can be "fixed" in the Ace framework (https://tools.ietf.org/html/draft-ietf-ace-oauth-authz-33#section-5.7.4) as well? By keeping the value integer or floating but adding a sentence saying that a constrained implementation might only use ints (which might be useful if the token use only int)?
