### ISSUE TITLE
Section 4.1.6.3 - The third paragraph is redundant

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#80]

**Comment by fpalombini** [comment]
Fixed in 9dae680

**Comment by jimsch** [comment]
Not fixed.

**Comment by fpalombini** [comment]
better now? 

The point is that 1st paragraph said: "this request is only accepted if you are deleting your own resource ("NODENAME")" and par 3 said "this request is only accepted if the node is authorized for this group ("GROUPNAME")". So it was 2 different things. Now I merged them, as they probably fit much better together in par 3...
