### ISSUE TITLE
Section 4.1.7.1 - Group rekeying if a public key is replaced

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#83]

**Comment by fpalombini** [comment]
@jimsch said:

> * In section 4.1.7.1 - If a public key is replaced, does this constitute a
> reason that a key roll over is going to be required?  Is this something that
> needs to be distributed proactively if it is allowed by the server since
> otherwise things may be really messed up?

The answer is not necessarily, but nothing stops the KDC to do a key rollover if it wants. 
I think this should be already clear, do we need any specific clarifications?
