### ISSUE TITLE
Section 4.3 - Two expiration times for the key material

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#84]

**Comment by fpalombini** [comment]
> * In section 4.3 - I don't know if this is worth while thinking about or
> not.  There may want to be two different expiration values that are defined
> in the system.  When you stop sending using the key material and when you
> stop receiving using the keying material.  These values would need to be
> contingent on a "key revocation" event as well.  The delta could be setup as
> a new group parameter with a default value set by the document.
>
