### ISSUE TITLE
Section 5 - Expand reasoning on not authorized (bullet 1 and 3)

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#86]

**Comment by fpalombini** [comment]
> * In Section 5 - For bullet 1 of bullet 3 - I think that the reasoning
> behind not authorized needs to be expanded.  For example it might say, the
> node is no longer authorized for that group. 
>

**Comment by fpalombini** [comment]
I hope this is a good enough clarification..
