### ISSUE TITLE
Role/functionality of "proxy signature checker"

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#91]

**Comment by fpalombini** [comment]
@jimsch said:
> There is a missing role/functionality that needs to be added to the
> document.  "proxy signature checker" has the ability to get the public keys
> associated with the different members of the group but does not get any
> access to the symmetric keying material
>

**Comment by fpalombini** [comment]
Actually, you do not need to be a member of the group (i.e. having done the join process) to get the public keys, so there is no need to define such a role. As long as you get access to the pub-key resource (by getting authorized by the AS), you can request those.

Will add some considerations about that in pub-key section.

**Comment by jimsch** [comment]
But this is something that I might want to control in order to restrict who can determine who is in the group.  This would be determinable by looking at the public key.

**Comment by fpalombini** [comment]
Had agreement that it's fine at the interim (OSCORE profile does define the role for monitor).
